### ISSUE TITLE
1.2.5 build fails on debian unstable armel and ppc64el architectures

### ISSUE THREAD

**Issue by snd1** [sadko4u/lsp-plugins#307]
lsp-plugins builds **for armel and ppc64el** will be removed from debian testing/unstable, because it doesn't build on armel and ppc64el anymore, while these architectures are official ones in debian. Sorry for my late bug report, i simply forgot to report this..

Why not using the default baseline? https://wiki.debian.org/InstructionSelection
Is there a chance to fix this? The bug and the build logs are linked below:

RM Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031962
Armel build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.5-1&stamp=1677023181&raw=0
Ppc64el build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=ppc64el&ver=1.2.5-1&stamp=1677023296&raw=0
All builds for 1.2.5: https://buildd.debian.org/status/package.php?p=lsp-plugins

**Comment by sadko4u** [comment]
Hello.

> Why not using the default baseline? https://wiki.debian.org/InstructionSelection

Because I'm building not for Debian only? There is also Windows platform which we are moving towards.

> Armel build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.5-1&stamp=1677023181&raw=0

The actual error is:
```
{standard input}:57: Error: selected processor does not support `vmrs r3,FPSCR' in ARM mode
{standard input}:89: Error: selected processor does not support `vmsr FPSCR,r1' in ARM mode
{standard input}:145: Error: selected processor does not support `vmsr FPSCR,r3' in ARM mode
```

It seems that we're trying to use the unsupported instruction by the architecture.

> Ppc64el build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=ppc64el&ver=1.2.5-1&stamp=1677023296&raw=0

The actual error is:
```
/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/lsp-plugin-fw-ui.o:(.toc+0x0): undefined reference to `lsp::ctl::Factory::pRoot'
```

This is very strange bug since the linker can not find the static member class defined here:
https://github.com/lsp-plugins/lsp-plugin-fw/blob/987e5929a942e0976b01315675ada2700cd62e46/src/main/ui/Factory.cpp#L28

We're trying to build LV2 TTL generator tool and get the error. But the LV2 TTL generator even doesn't need the UI-related stuff. I don't have any idea how this symbol appears in non-ui related code.

I need to reproduce these builds somehow.

**Comment by sadko4u** [comment]
@snd1 it seems that I found the issue.
In 1.2.5 there was additional metadata validator introduced and it seems that I forgot to add one dependency to it in the build.

Anyway, these patches should fix all your build problems:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/746181e62cf9525237a8e860d94ecbec6436694b
https://github.com/lsp-plugins/lsp-plugin-fw/commit/ed70058660be17e87d8a055f9024228b632ae7b8

**Comment by snd1** [comment]
Thanks, i applied these patches and the ppc64el build works now,

but the armel build still fails:
 ```
{standard input}:57: Error: selected processor does not support `vmrs r3,FPSCR' in ARM mode
{standard input}:89: Error: selected processor does not support `vmsr FPSCR,r1' in ARM mode {standard input}:145: Error: selected processor does not support `vmsr FPSCR,r3' in ARM mode
 ```
full armel log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.5-2&stamp=1677700028&raw=0

btw also the armhf build fails:
 ```
cc1plus: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
 ```
full armhf log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armhf&ver=1.2.5-2&stamp=1677699850&raw=0

but i fixed the armhf build with setting the flag +fp to
 ```
-march=armv7-a+fp
 ```
for hardware support for floating-point operations, see #309

armel does not have hardware support.

**Comment by sadko4u** [comment]
I think I need to add `armhf` as another platform with another flags.

**Comment by sadko4u** [comment]
Oh, it seems it detects the platform still as ARMv7 because it uses the `uname -m` to detect the platform:
```
echo "Architecture: arm32/arm32 (-march=armv7-a -marm)"
Architecture: arm32/arm32 (-march=armv7-a -marm)
echo "Features:     jack ladspa lv2 vst2 xdg"
```

I think explicitly setting `ARCHITECTURE=armel` for `make config` should fix the problem.

**Comment by sadko4u** [comment]
Also note that since 1.2.5 LSP plugins provide CLAP support

**Comment by sadko4u** [comment]
I think this patch should be enough:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/fd74a13b69570403cdd34c08e00002ba5072715f

**Comment by snd1** [comment]
uname -m is a real problem, because with that cross compiling can not work; we need to define the target host and not the host hardware for cross compiling.

the armhf build still fails with the same error with the last patch, the added armhf block is not detected:
 ```
echo "Architecture: arm32/arm32 (-march=armv7-a -marm)"
Architecture: arm32/arm32 (-march=armv7-a -marm)
```
Full build log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armhf&ver=1.2.5-3&stamp=1677720510&raw=0

**Comment by sadko4u** [comment]
Anyway, you can override the compilation flags and architecture by the variables:
`make config ARCHITECTURE=<target-architecture> ARCHTECTURE_CFLAGS=<your cflags>`

**Comment by sadko4u** [comment]
> we need to define the target host and not the host hardware for cross compiling.

For this case, the `ARCHITECTURE` parameter was introduced in makefiles.

**Comment by snd1** [comment]
I was not successful to override ARCHITECTURE and ARCHITECTURE_CFLAGS within the debian/rules file so far, it seems the system.mk always overrides my settings again.

But changing BUILD_ARCH to DEB_TARGET_ARCH for armel and armhf in the system.mk file did the trick, so like that the armhf build works at least again.

But when setting armel with the empty cflags the build still fails:
 ```
{standard input}:14964: Error: selected processor does not support `rev r8,r8' in ARM mode
{standard input}:14985: Error: selected processor does not support `rev r10,r10' in ARM mode
{standard input}:15006: Error: selected processor does not support `rev r9,r9' in ARM mode
{standard input}:15041: Error: selected processor does not support `rev r9,r8' in ARM mode
{standard input}:15042: Error: selected processor does not support `rev r8,r4' in ARM mode
{standard input}:15076: Error: selected processor does not support `rev r4,r2' in ARM mode
{standard input}:15077: Error: selected processor does not support `rev r2,ip' in ARM mode
{standard input}:15119: Error: selected processor does not support `rev r3,ip' in ARM mode
{standard input}:15120: Error: selected processor does not support `rev ip,r0' in ARM mode
{standard input}:15160: Error: selected processor does not support `rev r3,r0' in ARM mode
{standard input}:15161: Error: selected processor does not support `rev r0,ip' in ARM mode
{standard input}:15195: Error: selected processor does not support `rev r3,r0' in ARM mode
{standard input}:15196: Error: selected processor does not support `rev r0,r1' in ARM mode
{standard input}:15242: Error: selected processor does not support `rev r3,r3' in ARM mode
{standard input}:15243: Error: selected processor does not support `rev lr,lr' in ARM mode
{standard input}:15773: Error: selected processor does not support `rev r9,r9' in ARM mode
{standard input}:15800: Error: selected processor does not support `rev r8,r8' in ARM mode
{standard input}:15827: Error: selected processor does not support `rev r0,r0' in ARM mode
{standard input}:15856: Error: selected processor does not support `rev r1,r2' in ARM mode
{standard input}:15857: Error: selected processor does not support `rev r2,r3' in ARM mode
{standard input}:15898: Error: selected processor does not support `rev r3,ip' in ARM mode
{standard input}:15899: Error: selected processor does not support `rev ip,r1' in ARM mode
{standard input}:15938: Error: selected processor does not support `rev r3,ip' in ARM mode
{standard input}:15939: Error: selected processor does not support `rev ip,r1' in ARM mode
{standard input}:15978: Error: selected processor does not support `rev r3,ip' in ARM mode
{standard input}:15979: Error: selected processor does not support `rev ip,r1' in ARM mode
{standard input}:16018: Error: selected processor does not support `rev r3,ip' in ARM mode
{standard input}:16019: Error: selected processor does not support `rev ip,r1' in ARM mode
 ```
 Full build log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.5-4&stamp=1677884454&raw=0

**Comment by sadko4u** [comment]
It is very strange. On my raspberry PI:
```
sadko@rpi4b2g:~/git/lsp-plugins $ make config ARCHITECTURE=armel
make[1]: Entering directory '/home/sadko/git/lsp-plugins'
Configuring build...
Architecture: generic/armel ()
Features:     clap doc jack ladspa lv2 vst2 xdg
Configured OK
make[1]: Leaving directory '/home/sadko/git/lsp-plugins'
```

For armhf:
```
sadko@rpi4b2g:~/git/lsp-plugins $ make config ARCHITECTURE=armhf
make[1]: Entering directory '/home/sadko/git/lsp-plugins'
Configuring build...
Architecture: arm32/arm32 (-march=armv7-a+fp -marm)
Features:     clap doc jack ladspa lv2 vst2 xdg
Configured OK
make[1]: Leaving directory '/home/sadko/git/lsp-plugins'
```

Oh... Maybe you didn't override the `make/system.mk` in the `lsp-plugins` package, too. The patch I've provided for `lsp-plugin-fw` can also be applied to `lsp-plugins` makefile.

**Comment by snd1** [comment]
Sorry, no it was my fault, i was not trying hard enough with the rules file, now it works with overriding correctly.

I added '-mfloat-abi=softfp' to the armel cflags but get the same errors
 ```
{standard input}:16019: Error: selected processor does not support `rev ip,r1' in ARM mode
...
 ```
so i wonder if armel build can be fixed at all? if not, then i need to disable the architecture for lsp-plugins

**Comment by sadko4u** [comment]
For me, I have succeeded the `armel` build on my Raspberry Pi 4 with Raspbian on board.

I just added these lines to the `make/system.mk`:

https://github.com/sadko4u/lsp-plugins/blob/fe42ac0ffc5372d061c9d6ab7795998e05e701aa/make/system.mk#L57-L64

And all went well:

```
sadko@rpi4b2g:~/git/lsp-plugins $ make config ARCHITECTURE=armel
make[1]: Entering directory '/home/sadko/git/lsp-plugins'
Configuring build...
Architecture: generic/armel ()
Features:     clap doc jack ladspa lv2 vst2 xdg
Configured OK
make[1]: Leaving directory '/home/sadko/git/lsp-plugins'

sadko@rpi4b2g:~/git/lsp-plugins $ make -j2
make[1]: Entering directory '/home/sadko/git/lsp-plugins/src'
make[2]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-plugin-fw'
make[3]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-plugin-fw/src'
make [lsp-common-lib]
make [lsp-dsp-lib]
make[4]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-common-lib'
make[4]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-dsp-lib'
make[5]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-common-lib/src'
  g++  [lsp-common-lib] main/bits.cpp
make[5]: Entering directory '/home/sadko/git/lsp-plugins/modules/lsp-dsp-lib/src'
  g++  [lsp-dsp-lib] main/dsp.cpp
  g++  [lsp-common-lib] main/debug.cpp
  g++  [lsp-dsp-lib] main/generic/generic.cpp
  g++  [lsp-common-lib] main/singletone.cpp

....

  g++ [vst2] spectrum-analyzer-x2.cpp
  g++ [vst2] spectrum-analyzer-x4.cpp
  g++ [vst2] spectrum-analyzer-x8.cpp
  g++ [vst2] surge-filter-mono.cpp
  g++ [vst2] surge-filter-stereo.cpp
  g++ [vst2] trigger-midi-mono.cpp
  g++ [vst2] trigger-midi-stereo.cpp
  g++ [vst2] trigger-mono.cpp
  g++ [vst2] trigger-stereo.cpp
make[4]: Leaving directory '/home/sadko/git/lsp-plugins/.build/target/lsp-plugin-fw/vst2'
make[3]: Leaving directory '/home/sadko/git/lsp-plugins/modules/lsp-plugin-fw/src'
make[2]: Leaving directory '/home/sadko/git/lsp-plugins/modules/lsp-plugin-fw'
make[1]: Leaving directory '/home/sadko/git/lsp-plugins/src'
sadko@rpi4b2g:~/git/lsp-plugins $ 
```

I think it is much easier just compile `armel` as a `generic` architecture without the additional optimizations for NEON and some other stuff like endianess as it is done for `ppc64el` as you see in the `make config` output:
```
Architecture: generic/armel
```

Maybe I'm wrong in understanding the environment.
I need to understand the difference between `armel` and standard `armv7a` platform in case of C/C++ predefined macros. If there is a macro that allows to distinguish `armel` from `armv7a`, then it is not hard to fix the build.

About your build error: we're trying to compile function stat perform byte reverse of the value for endianess conversions. The code assumes that we have the corresponding instruction. But actually the compiler does not allow to use it because of some restrictions applied by the compilation flags.

I think one good point could be to dump all predefined macros for all 32-bit ARM architectures with the following command:
```
echo | g++ <architecture-dependent compilation flags> -dM -E -x c++ - | sort
```

and compare them one to another.

It could be nice to have such output in your builds to understand the difference.

**Comment by sadko4u** [comment]
@snd1 I did additional code refactoring in the `lsp-common-lib` module. Probably this will help you with build for `armel`:

https://github.com/lsp-plugins/lsp-common-lib/commit/3ef9acb53be5da7528d3e31590eb62f69b4838d2

**Comment by snd1** [comment]
Thank you! Should i apply the whole merge from https://github.com/lsp-plugins/lsp-common-lib/commit/3ef9acb53be5da7528d3e31590eb62f69b4838d2 or only a part of it? Because if i apply all then all build fails even on amd64:
 ```
make[6]: *** No rule to make target '/<<PKGBUILDDIR>>/modules/lsp-common-lib/include/lsp-plug.in/common/arch/x86/bits.h', needed by '/<<PKGBUILDDIR>>/.build/target/lsp-runtime-lib/main/resource/Compressor.o'.  Stop.
 ```

with armel cross compiling (via amd64 machine) it stops with:
```
mkdir -p /<<PKGBUILDDIR>>/.build/target/lsp-runtime-lib/main/ipc/
arm-linux-gnueabi-g++ -o /<<PKGBUILDDIR>>/.build/target/lsp-runtime-lib/main/ipc/NativeExecutor.o -c main/ipc/NativeExecutor.cpp -fPIC -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_RUNTIME_LIB_BUILTIN -fvisibility=hidden -DUSE_LSP_COMMON_LIB -DUSE_LSP_LLTL_LIB -DUSE_LIBPTHREAD -DUSE_LIBDL -DUSE_LIBSNDFILE   -I"/<<PKGBUILDDIR>>/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN    -I"/<<PKGBUILDDIR>>/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN
{standard input}: Assembler messages:
{standard input}:89: Error: selected processor does not support `ldrex ip,[r4]' in ARM mode
{standard input}:91: Error: selected processor does not support `strexeq ip,r5,[r4]' in ARM mode
{standard input}:205: Error: selected processor does not support `ldrex r3,[r4]' in ARM mode
{standard input}:207: Error: selected processor does not support `strexeq r3,r1,[r4]' in ARM mode
{standard input}:340: Error: selected processor does not support `ldrex r2,[r4]' in ARM mode
{standard input}:342: Error: selected processor does not support `strexeq r2,r3,[r4]' in ARM mode
make[6]: *** [Makefile:131: /<<PKGBUILDDIR>>/.build/target/lsp-runtime-lib/main/ipc/Mutex.o] Error 1
make[6]: *** Waiting for unfinished jobs....
{standard input}: Assembler messages:
{standard input}:77: Error: selected processor does not support `ldrex lr,[r2]' in ARM mode
{standard input}:79: Error: selected processor does not support `strexeq lr,r3,[r2]' in ARM mode
{standard input}:157: Error: selected processor does not support `ldrex r1,[r2]' in ARM mode
{standard input}:158: Error: selected processor does not support `strex r3,r0,[r2]' in ARM mode
{standard input}:241: Error: selected processor does not support `ldrex r2,[r5]' in ARM mode
{standard input}:242: Error: selected processor does not support `strex r3,r4,[r5]' in ARM mode
{standard input}:280: Error: selected processor does not support `ldrex r3,[r5]' in ARM mode
{standard input}:282: Error: selected processor does not support `strexeq r3,r7,[r5]' in ARM mode
{standard input}:560: Error: selected processor does not support `ldrex r3,[r4]' in ARM mode
{standard input}:562: Error: selected processor does not support `strexeq r3,r5,[r4]' in ARM mode
{standard input}:645: Error: selected processor does not support `ldrex r1,[r4]' in ARM mode
{standard input}:646: Error: selected processor does not support `strex r2,r3,[r4]' in ARM mode
{standard input}:708: Error: selected processor does not support `ldrex r2,[r4]' in ARM mode
{standard input}:709: Error: selected processor does not support `strex r3,r6,[r4]' in ARM mode
```
btw armel is armv5 https://wiki.debian.org/ArmEabiPort

when i cross compile for an arm (armel or armhf) architecture i also see this problem:
```
ld -o /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/lsp-lltl-lib.o -r  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/darray.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/iterator.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/parray.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/phashset.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/pphash.o  /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/types.o 
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o: error adding symbols: file in wrong format
make[6]: *** [Makefile:140: /<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/lsp-lltl-lib.o] Error 1
make[6]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/src'
make[5]: *** [Makefile:53: compile] Error 2
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib'
make[4]: *** [Makefile:713: LSP_LLTL_LIB] Error 2
```
since i compile this on my laptop these build logs are not online, if you need them i can send those via email.

**Comment by snd1** [comment]
> Also note that since 1.2.5 LSP plugins provide CLAP support

I will add the CLAP plugins after debian bookworm (debian 12) is released, because it needs a new package for the CLAP plugins, and bookworm is currently in freeze mode https://release.debian.org/bookworm/freeze_policy.html

**Comment by sadko4u** [comment]
> Thank you! Should i apply the whole merge from https://github.com/lsp-plugins/lsp-common-lib/commit/3ef9acb53be5da7528d3e31590eb62f69b4838d2 or only a part of it? Because if i apply all then all builds fail, even on amd64:

I think the best solution for you is just to remove all `Makefile.*.d` files (which contain dependencies between headers and source code files) for 1.2.5. I spent couple of time today for generating proper dependency files for all subprojects.

Then it should build I hope.

**Comment by sadko4u** [comment]
```
{standard input}:89: Error: selected processor does not support `ldrex ip,[r4]' in ARM mode
{standard input}:91: Error: selected processor does not support `strexeq ip,r5,[r4]' in ARM mode
```

Seems that `armel` means ARMv5 architecture. So I need to understand how to replace these instructions.

**Comment by sadko4u** [comment]
@snd1 I have reorganized the code to add support of ARMv5 in `lsp-common-lib`. The previous patch I've provided has been updated and now is the following:

https://github.com/lsp-plugins/lsp-common-lib/commit/e3610eb582ed2fd1e3895b50081447ae006d8aa7

To build properly, just remove all `Makefile.*.d` files in the source code tree.

**Comment by snd1** [comment]
For the overview what ive changed, I picked following commits from your merge:
Code-refactoring.patch
Updated-endian-stuff.patch
Added-legacy-ARM-atomic-implementation.patch
Code-update.patch
Updated-bit-operations.patch

**Comment by sadko4u** [comment]
> Unfortunately the build still fails with the same error on amd64

Did your remove `modules/lsp-runtime-lib/src/Makefile.d` and all other `Makefile.d` recursively?

**Comment by snd1** [comment]
Yes i ran `find -type f -name Makefile.d* -delete` before configure, but it still fails.

This log is from amd64 build: https://privatebin.io/?1d079d47d55cb9d1#8zadSck999sNqvy39VphN9EjKRhTxRiaVKhcgvX2Xdts

**Comment by sadko4u** [comment]
The error is:

```
/<<PKGBUILDDIR>>/modules/lsp-common-lib/src/Makefile.d:35: *** multiple target patterns.  Stop.
```

Does this file exist? Should be removed

**Comment by sadko4u** [comment]
Issued the `find -type f -name 'Makefile*.d' -delete`.

The build worked fine.

**Comment by snd1** [comment]
Thanks the build for amd64 and most other archs work again.

Armel still fails with a few errors from Assembler messages:
```
{standard input}: Assembler messages:
{standard input}:58: Error: selected processor does not support `vmrs r2,FPSCR' in ARM mode
{standard input}:114: Error: selected processor does not support `vmsr FPSCR,r2' in ARM mode
{standard input}:194: Error: selected processor does not support `vmsr FPSCR,r3' in ARM mode
```
Build Log: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=armel&ver=1.2.5-6&stamp=1678254534&raw=0

And arm64 and sh4 build fails too which were working before, i think for arm64 i need to define in d/rules probably now too.
All currently build logs: https://buildd.debian.org/status/package.php?p=lsp-plugins#problem-8

**Comment by sadko4u** [comment]
> Armel still fails with a few errors from Assembler messages:

I see your configuration forces to use `arm5t`. And it seems that `lsp-dsp-lib` is failing to build because of the unsupported instructions. I'll fix it soon.

> And arm64 build fails

We see that it tries to use lsp::int_log2 function:
```
g++ -o /<<PKGBUILDDIR>>/.build/target/lsp-tk-lib/main/style/Style.o -c main/style/Style.cpp -fPIC -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_TK_LIB_BUILTIN -fvisibility=hidden -DUSE_LSP_COMMON_LIB -DUSE_LSP_LLTL_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_WS_LIB -DUSE_LIBPTHREAD -DUSE_LIBDL -DUSE_LIBSNDFILE -DUSE_LIBCAIRO -DUSE_LIBFREETYPE -DUSE_LIBX11 -DUSE_LIBXRANDR   -I"/<<PKGBUILDDIR>>/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN -I"/<<PKGBUILDDIR>>/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN   -I/usr/include/opus -I/usr/include/aarch64-linux-gnu  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16  -I/usr/include/freetype2 -I/usr/include/libpng16    -I"/<<PKGBUILDDIR>>/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN
main/prop/specific/GraphFrameData.cpp: In member function ‘bool lsp::tk::GraphFrameData::resize_buffer(size_t, size_t)’:
main/prop/specific/GraphFrameData.cpp:174:55: error: ‘int_log2’ is not a member of ‘lsp’
  174 |             size_t cap      = (rows > 0) ? (1 << lsp::int_log2(rows)) : 0;
      |                                                       ^~~~~~~~
```

Which is included by:
```
#include <lsp-plug.in/common/bits.h>
```

Then by:
```
#include <lsp-plug.in/common/arch/aarch64/bits/int_log2.h>
```

Wrongly applied patches?

> and sh4 build fails

Something got wrong with the project's manifest file. I see that there were no resources compressed:

```
Execution time: 0.06 s
echo "respack lsp-plugin-fw-res.cpp"
respack lsp-plugin-fw-res.cpp
/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/utils-bin/respack -o "/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/lsp-plugin-fw-res.cpp" -i "/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res" -c "/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res-checksum.json"
Packing resources to /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/lsp-plugin-fw-res.cpp from /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res
Input size: 0, compressed size: 0, compression ratio: nan
Execution time: 0.06 s
g++ -o /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/lsp-plugin-fw-res.o -c /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/lsp-plugin-fw-res.cpp -fPIC -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr\" -DUSE_LSP_COMMON_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_DSP_UNITS -DUSE_LSP_LLTL_LIB -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_PLUGIN_FW -DUSE_LSP_3RD_PARTY -DUSE_LIBPTHREAD -DUSE_LIBDL -DUSE_LIBJACK -DUSE_LIBSNDFILE -DUSE_LSP_R3D_BASE_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_TK_LIB -DUSE_LSP_WS_LIB -DUSE_LIBX11 -DUSE_LIBXRANDR -DUSE_LIBCAIRO -DUSE_LIBFREETYPE -DUSE_LIBLADSPA -DUSE_LIBLV2 -DUSE_LSP_PLUGINS_SHARED -DUSE_LIBGL     -I"/<<PKGBUILDDIR>>/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-dsp-units/include" -DLSP_DSP_UNITS_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-3rd-party/include"        -I/usr/include/opus -I/usr/include/sh4-linux-gnu   -I"/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib/include" -DLSP_R3D_BASE_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN      -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/sh4-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16   -I/usr/include/freetype2 -I/usr/include/libpng16       -I"/<<PKGBUILDDIR>>/modules/lsp-plugins-shared/include" -DLSP_PLUGINS_SHARED_BUILTIN -DLSP_PLUGINS_SHARED_PUBLISHER  
echo "respack lsp-plugin-fw-res.cpp"
respack lsp-plugin-fw-res.cpp
/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/utils-bin/respack -o "/<<PKGBUILDDIR>>/.build/target/lsp-plugin-fw/lsp-plugin-fw-res.cpp" -i "/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res" -c "/<<PKGBUILDDIR>>/.build/target/lsp-plugin-fw/res-checksum.json"
Packing resources to /<<PKGBUILDDIR>>/.build/target/lsp-plugin-fw/lsp-plugin-fw-res.cpp from /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res
Input size: 0, compressed size: 0, compression ratio: nan

```

It seems that the `repository` utility didn't find any files to put to the temporary directory for archiving:
```
echo "  /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/utils-bin/repository"
  /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/utils-bin/repository
/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/utils-bin/repository -o "/<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res" -d "ARTIFACT_ID=lsp-plugins" -d "ARTIFACT_DESC=Linux Studio Plugins" -d "ARTIFACT_VERSION=1.2.5" -m "/<<PKGBUILDDIR>>/res/manifest.json" "/<<PKGBUILDDIR>>" "/<<PKGBUILDDIR>>/modules/*"
Generating resource tree
  defined variable: ARTIFACT_ID = lsp-plugins
  defined variable: ARTIFACT_DESC = Linux Studio Plugins
  defined variable: ARTIFACT_VERSION = 1.2.5
  target dir: /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res
  writing manifest: /<<PKGBUILDDIR>>/.build/host/lsp-plugin-fw/res/manifest.json
Execution time: 0.06 s
```

As you see, it has written the `manifest.json` but something went wrong.

**Comment by sadko4u** [comment]
FYI for `lsp-common-lib` I've created `hotfix` branch which starts from `1.2.5` and moved all patches there:
https://github.com/lsp-plugins/lsp-common-lib/tree/hotfix

**Comment by sadko4u** [comment]
Hotfix branch for the `lsp-dsp-lib`: https://github.com/lsp-plugins/lsp-dsp-lib/tree/hotfix

**Comment by sadko4u** [comment]
`hotfix` branch for `lsp-plugins`: https://github.com/sadko4u/lsp-plugins/tree/hotfix

**Comment by sadko4u** [comment]
The build for `armv5t` should be fixed now.

**Comment by sadko4u** [comment]
`hotfix` branch for `lsp-runtime-lib`: https://github.com/lsp-plugins/lsp-runtime-lib/tree/hotfix

**Comment by sadko4u** [comment]
Also @snd1 I'm very close to issue the 1.2.6 release.
Is there a good reason to test the development branch on debian build system before we fall into problems of building already released 1.2.6 version?

**Comment by snd1** [comment]
thanks, armel build now works!!!

but now mips64el fails to build:
```
g++ -o /<<PKGBUILDDIR>>/.build/target/lsp-plugin-fw/main/ctl/simple/Led.o -c main/ctl/simple/Led.cpp -fPIC -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr\" -DUSE_LSP_COMMON_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_DSP_UNITS -DUSE_LSP_LLTL_LIB -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_PLUGIN_FW -DUSE_LSP_3RD_PARTY -DUSE_LIBPTHREAD -DUSE_LIBDL -DUSE_LIBJACK -DUSE_LIBSNDFILE -DUSE_LSP_R3D_BASE_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_TK_LIB -DUSE_LSP_WS_LIB -DUSE_LIBX11 -DUSE_LIBXRANDR -DUSE_LIBCAIRO -DUSE_LIBFREETYPE -DUSE_LIBLADSPA -DUSE_LIBLV2 -DUSE_LSP_PLUGINS_SHARED -DUSE_LIBGL     -I"/<<PKGBUILDDIR>>/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-dsp-lib/include" -DLSP_DSP_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-dsp-units/include" -DLSP_DSP_UNITS_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-3rd-party/include"        -I/usr/include/opus -I/usr/include/mips64el-linux-gnuabi64   -I"/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib/include" -DLSP_R3D_BASE_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN  -I"/<<PKGBUILDDIR>>/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN      -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/mips64el-linux-gnuabi64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16   -I/usr/include/freetype2 -I/usr/include/libpng16       -I"/<<PKGBUILDDIR>>/modules/lsp-plugins-shared/include" -DLSP_PLUGINS_SHARED_BUILTIN -DLSP_PLUGINS_SHARED_PUBLISHER  
In file included from /<<PKGBUILDDIR>>/modules/lsp-tk-lib/include/lsp-plug.in/tk/tk.h:102,
                 from /<<PKGBUILDDIR>>/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/ctl/helpers.h:31,
                 from /<<PKGBUILDDIR>>/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/ctl.h:30,
                 from main/ctl/simple/Led.cpp:22:
/<<PKGBUILDDIR>>/modules/lsp-tk-lib/include/lsp-plug.in/tk/prop/multi/Vector2D.h:86:43: internal compiler error: Segmentation fault
   86 |                 inline float        phi() const                 { return fPhi;                  }
      |                                           ^~~~~
0x121520a8b internal_error(char const*, ...)
	???:0
0x120d74d89 check_qualified_type(tree_node const*, tree_node const*, int)
	???:0
0x120d74f03 get_qualified_type(tree_node*, int)
	???:0
0x120d836c7 build_qualified_type(tree_node*, int)
	???:0
0x1202761fb build_memfn_type(tree_node*, tree_node*, int, cp_ref_qualifier)
	???:0
0x120263e0b grokdeclarator(cp_declarator const*, cp_decl_specifier_seq*, decl_context, int, tree_node**)
	???:0
0x120270213 grokmethod(cp_decl_specifier_seq*, cp_declarator const*, tree_node*)
	???:0
0x12037ab2b c_parse_file()
	???:0
0x1204a659f c_common_parse_file()
```
full build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=mips64el&ver=1.2.5-7&stamp=1678396332&raw=0
all other builds: https://buildd.debian.org/status/package.php?p=lsp-plugins#problem-1

I will test the dev branch on my (amd64) laptop.

**Comment by sadko4u** [comment]
Internal compiler error... I think it is not related to LSP :)

**Comment by sadko4u** [comment]
Have you applied this patch?
https://github.com/sadko4u/lsp-plugins/issues/307#issuecomment-1460863301

I see the `O_DIRECT` error for this build:
https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=hurd-i386&ver=1.2.5-7&stamp=1678396840&raw=0

**Comment by snd1** [comment]
Do i still need to remove some Makefiles or even all Makfile*.d in lsp-plugins?

> Have you applied this patch? [#307 (comment)](https://github.com/sadko4u/lsp-plugins/issues/307#issuecomment-1460863301)
> 
> I see the `O_DIRECT` error for this build: https://buildd.debian.org/status/fetch.php?pkg=lsp-plugins&arch=hurd-i386&ver=1.2.5-7&stamp=1678396840&raw=0

Damn this one i forgot, ill add it now.

> > I will test the dev branch on my (amd64) laptop.
> 
> I thought it could be a good option to test the `dev` branch on the Debian build system before it becomes issued.
> 
> Also It's strange that several platforms have problems building lsp-plugins like ia64, hurd-i386, sh4 and x32. It is interesting for me to make them building the code but I need something like shell access to do the manual job.

Yes, we need cross compiling working, then i can test more archs directly on my device. the problem for cross building lays in the linker here somehow?
```
ld   [lsp-r3d-base-lib] lsp-r3d-base-lib.o
ld -o /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/lsp-r3d-base-lib.o -r  /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o 
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: echo "  arm-linux-gnueabi-g++  [lsp-lltl-lib] main/darray.cpp"
/<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: relocations in generic ELF (EM: 40)
ld: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o: error adding symbols: file in wrong format
make[6]: *** [Makefile:140: /<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/lsp-r3d-base-lib.o] Error 1
```
Same with some other object files. `make clean` does not help.

The dev build does not work, i copied the missing modules from 1.2.5, then the build stops at:
```
Architecture: x86_64/x86_64 ()
echo "Features:     jack ladspa lv2 vst2 xdg"
Features:     jack ladspa lv2 vst2 xdg
echo "Configured OK"
Configured OK
make[3]: Leaving directory '/<<PKGBUILDDIR>>'
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   dh_auto_configure
   dh_auto_build
	make -j6 "INSTALL=install --strip-program=true"
make[1]: Entering directory '/<<PKGBUILDDIR>>'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
make -C "/<<PKGBUILDDIR>>/src" all VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" DESTDIR=""
make[2]: Entering directory '/<<PKGBUILDDIR>>/src'
make -C "/<<PKGBUILDDIR>>/modules/lsp-plugin-fw" all VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk"
make[3]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-plugin-fw'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
make -C "/<<PKGBUILDDIR>>/modules/lsp-plugin-fw/src" all VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" DESTDIR=""
make[4]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-plugin-fw/src'
echo "make [lsp-common-lib]"
echo "make [lsp-dsp-lib]"
echo "make [lsp-dsp-units]"
make [lsp-common-lib]
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-common-lib"
make [lsp-dsp-lib]
make [lsp-dsp-units]
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-dsp-lib"
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-dsp-units"
echo "make [lsp-lltl-lib]"
echo "make [lsp-runtime-lib]"
make [lsp-lltl-lib]
echo "make [lsp-r3d-base-lib]"
make -C "/<<PKGBUILDDIR>>/modules/lsp-common-lib" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
make [lsp-runtime-lib]
make [lsp-r3d-base-lib]
make -C "/<<PKGBUILDDIR>>/modules/lsp-dsp-lib" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
make -C "/<<PKGBUILDDIR>>/modules/lsp-dsp-units" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib"
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-runtime-lib"
mkdir -p "/<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib"
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-common-lib'
make[5]: *** No rule to make target 'compile'.  Stop.
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-lib'
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-common-lib'
make[5]: *** No rule to make target 'compile'.  Stop.
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-lib'
make[4]: *** [Makefile:712: LSP_DSP_LIB] Error 2
make[4]: *** Waiting for unfinished jobs....
make -C "/<<PKGBUILDDIR>>/modules/lsp-lltl-lib" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-units'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
make[4]: *** [Makefile:713: LSP_COMMON_LIB] Error 2
make -C "/<<PKGBUILDDIR>>/modules/lsp-runtime-lib" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
make -C "/<<PKGBUILDDIR>>/modules/lsp-dsp-units/src" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" DESTDIR=""
make -C "/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" NO_DEPENDENCIES="1" DEMO_TEST="0"
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-runtime-lib'
make[5]: *** No rule to make target 'compile'.  Stop.
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-runtime-lib'
make[4]: *** [Makefile:713: LSP_RUNTIME_LIB] Error 2
make -C "/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/src" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" DESTDIR=""
make[5]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
make -C "/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib/src" compile VERBOSE="1" CONFIG="/<<PKGBUILDDIR>>/.config.mk" DESTDIR=""
make[6]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/src'
make[6]: *** No rule to make target '/<<PKGBUILDDIR>>/modules/lsp-common-lib/include/lsp-plug.in/common/types.h', needed by '/<<PKGBUILDDIR>>/.build/target/lsp-lltl-lib/main/bitset.o'.  Stop.
make[6]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib/src'
make[5]: *** [Makefile:53: compile] Error 2
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-lltl-lib'
make[4]: *** [Makefile:713: LSP_LLTL_LIB] Error 2
make[6]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib/src'
make[6]: *** No rule to make target '/<<PKGBUILDDIR>>/modules/lsp-common-lib/include/lsp-plug.in/common/types.h', needed by '/<<PKGBUILDDIR>>/.build/target/lsp-r3d-base-lib/main/base_backend.o'.  Stop.
make[6]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib/src'
make[5]: *** [Makefile:53: compile] Error 2
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-r3d-base-lib'
make[4]: *** [Makefile:713: LSP_R3D_BASE_LIB] Error 2
make[6]: Entering directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-units/src'
make[6]: *** No rule to make target '/<<PKGBUILDDIR>>/modules/lsp-common-lib/include/lsp-plug.in/common/types.h', needed by '/<<PKGBUILDDIR>>/.build/target/lsp-dsp-units/main/3d/Allocator.o'.  Stop.
make[6]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-units/src'
make[5]: *** [Makefile:53: compile] Error 2
make[5]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-dsp-units'
make[4]: *** [Makefile:713: LSP_DSP_UNITS] Error 2
make[4]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-plugin-fw/src'
make[3]: *** [Makefile:67: all] Error 2
make[3]: Leaving directory '/<<PKGBUILDDIR>>/modules/lsp-plugin-fw'
make[2]: *** [Makefile:155: all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
make[1]: *** [Makefile:68: all] Error 2
```

**Comment by sadko4u** [comment]
> Do i still need to remove some Makefiles or even all Makfile*.d in lsp-plugins?

Yes, until 1.2.6 gets issued. That's because I did file renames and moves but didn't update all `Makefile.d` for all modules in the patch.

**Comment by sadko4u** [comment]
> The dev build does not work, i copied the missing modules from 1.2.5, then the build stops at:

The development branch requires to fetch all dependencies first (due to some reasons we don't use git submodules).
So the overall build process should look like:
```
make config
make fetch
make
make install
```

**Comment by sadko4u** [comment]
> Yes, we need cross compiling working, then i can test more archs directly on my device. the problem for cross building lays in the linker here somehow?

Yes, seems that we're trying to use the default linker instead of the system-specific one. I think we need to play with `LD`, `CC`, `CXX` environment variables.

**Comment by snd1** [comment]
> > The dev build does not work, i copied the missing modules from 1.2.5, then the build stops at:
> 
> The development branch requires to fetch all dependencies first (due to some reasons we don't use git submodules). So the overall build process should look like:
> 
> ```
> make config
> make fetch
> make
> make install
> ```

the sbuild and pbuilder builds fail with make fetch, because of wrong server certificate verification >_<
```
echo "Architecture: x86_64/x86_64 ()"
Architecture: x86_64/x86_64 ()
echo "Features:     jack ladspa lv2 vst2 xdg"
Features:     jack ladspa lv2 vst2 xdg
echo "Configured OK"
Configured OK
make[3]: Leaving directory '/<<PKGBUILDDIR>>'
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
/usr/bin/make fetch
make[2]: Entering directory '/<<PKGBUILDDIR>>'
test -f "/<<PKGBUILDDIR>>/.config.mk" || (echo "System not properly configured. Please launch 'make config' first" && exit 1)
echo "Fetching desired source code dependencies"
Fetching desired source code dependencies
/usr/bin/make -f "make/modules.mk" fetch VERBOSE="1" BASEDIR="/<<PKGBUILDDIR>>" CONFIG="/<<PKGBUILDDIR>>/.config.mk"
make[3]: Entering directory '/<<PKGBUILDDIR>>'
echo "Cloning https://github.com/lsp-plugins/lsp-common-lib.git -> /<<PKGBUILDDIR>>/modules/lsp-common-lib [1.0.25]"
Cloning https://github.com/lsp-plugins/lsp-common-lib.git -> /<<PKGBUILDDIR>>/modules/lsp-common-lib [1.0.25]
test -f "/<<PKGBUILDDIR>>/modules/lsp-common-lib/.git/config" || git clone "https://github.com/lsp-plugins/lsp-common-lib.git" "/<<PKGBUILDDIR>>/modules/lsp-common-lib"
Cloning into '/<<PKGBUILDDIR>>/modules/lsp-common-lib'...
fatal: unable to access 'https://github.com/lsp-plugins/lsp-common-lib.git/': server certificate verification failed. CAfile: none CRLfile: none
make[3]: *** [make/modules.mk:86: LSP_COMMON_LIB] Error 128
```
I use those tools to build debian packages.

**Comment by sadko4u** [comment]
Nice to see. Do we have any unclosed problems at this moment?

**Comment by snd1** [comment]
> Nice to see. Do we have any unclosed problems at this moment?

Nope, not really for 1.2.5, at least all packages for official architectures have been built. So only some unofficial ones could need fixes, anyways this is not urgent. Basically this bug can be closed, and maybe we open a new one for cross compiling?

With a workaround i could fix make fetch in pbuilder and the 1.2.6 build looks fine with amd64! :)

**Comment by snd1** [comment]
Btw i have to add: Thank You for all your great work!

**Comment by sadko4u** [comment]
Yes, I think we can do another issue for cross-compiling. There is purpose in it but I believe we need to start with something trivial. For example, with `lsp-common-lib` or `lsp-runtime-lib`.

**Comment by sadko4u** [comment]
The ticket will be closed after 1.2.6 release.

**Comment by sadko4u** [comment]
Changes added to 1.2.6 release.
